apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    io.fossology.service: db
  name: db
spec:
  serviceName: "db"
  replicas: 1
  selector:
    matchLabels:
      io.fossology.service: db
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.fossology.service: db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: fossology
            - name: POSTGRES_INITDB_ARGS
              value: '-E SQL_ASCII'
            - name: POSTGRES_PASSWORD
              value: fossy
            - name: POSTGRES_USER
              value: fossy
          image: postgres:9.6
          ports:
            - containerPort: 5432
          name: db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: database
      restartPolicy: Always
      volumes:
        - name: database
          persistentVolumeClaim:
            claimName: database
status:
  replicas: 1