apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.fossology.service: nomos
  name: nomos
spec:
  replicas: 1
  selector:
    matchLabels:
      io.fossology.service: nomos
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.fossology.service: nomos
    spec:
      containers:
        - args:
            - agent
          env:
            - name: FOSSOLOGY_DB_HOST
              value: db
            - name: FOSSOLOGY_DB_NAME
              value: fossology
            - name: FOSSOLOGY_DB_PASSWORD
              value: fossy
            - name: FOSSOLOGY_DB_USER
              value: fossy
            - name: FOSSOLOGY_SCHEDULER_HOST
              value: scheduler
          image: fossology:nomos
          imagePullPolicy: Never
          name: nomos
          resources: {}
      restartPolicy: Always
status: {}
