apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.fossology.service: scheduler
  name: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      io.fossology.service: scheduler
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        fossology.cmd: fossology convert
        fossology.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.fossology.service: scheduler
    spec:
      containers:
        - args:
            - scheduler
          env:
            - name: FOSSOLOGY_DB_HOST
              value: db
            - name: FOSSOLOGY_DB_NAME
              value: fossology
            - name: FOSSOLOGY_DB_PASSWORD
              value: fossy
            - name: FOSSOLOGY_DB_USER
              value: fossy
          image: fossology:scheduler
          imagePullPolicy: Never
          livenessProbe:
            exec:
              command:
                - "true"
            failureThreshold: 2
            periodSeconds: 5
            timeoutSeconds: 5
          name: scheduler
          resources: {}
          volumeMounts:
            - mountPath: /srv/fossology/repository/
              name: repository
      restartPolicy: Always
      volumes:
        - name: repository
          persistentVolumeClaim:
            claimName: repository
status: {}
