apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.fossology.service: web
  name: web
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 80
  selector:
    io.fossology.service: web
  type: LoadBalancer
status:
  loadBalancer: {}
